#pragma once

#ifndef DESPOOF_DEFAULT_INTERVAL
# define DESPOOF_DEFAULT_INTERVAL 750
#endif

#ifndef DESPOOF_DEFAULT_DEBUGGER
# define DESPOOF_DEFAULT_DEBUGGER "ntsd -server npipe:pipe=despoof_debug -noio"
#endif

#ifndef DESPOOF_SERVICE_NAME
# define DESPOOF_SERVICE_NAME "despoof"
#endif

#ifndef DESPOOF_SERVICE_DESCRIPTION
# define DESPOOF_SERVICE_DESCRIPTION "Defense against ARP spoofing - Regularly updates the ARP caches of the configured gateways with the local MAC address"
#endif

#ifndef DESPOOF_DEFAULT_NET_MODULE
# define DESPOOF_DEFAULT_NET_MODULE "pcap"
#endif

#ifdef DESPOOF_DEFAULT_LOG_MODULE_ALL
# define DESPOOF_DEFAULT_LOG_MODULE DESPOOF_DEFAULT_LOG_MODULE_ALL
#else
# ifndef DESPOOF_DEFAULT_LOG_MODULE_NOSVC
#  define DESPOOF_DEFAULT_LOG_MODULE_NOSVC "console"
# endif

# ifndef DESPOOF_DEFAULT_LOG_MODULE_SVC
#  define DESPOOF_DEFAULT_LOG_MODULE_SVC "file"
# endif

# ifdef BUILD_SERVICE
#  define DESPOOF_DEFAULT_LOG_MODULE DESPOOF_DEFAULT_LOG_MODULE_SVC
# else
#  define DESPOOF_DEFAULT_LOG_MODULE DESPOOF_DEFAULT_LOG_MODULE_NOSVC
# endif
#endif


#define DESPOOF_INT_WIDEN2(x) L##x
#define DESPOOF_INT_WIDEN(x) DESPOOF_INT_WIDEN2(x)

#define DESPOOF_WIDE_SERVICE_NAME DESPOOF_INT_WIDEN(DESPOOF_SERVICE_NAME)
#define DESPOOF_WIDE_SERVICE_DESCRIPTION DESPOOF_INT_WIDEN(DESPOOF_SERVICE_DESCRIPTION)
