#pragma once

#ifndef DESPOOF_DEFAULT_DEBUGGER
# define DESPOOF_DEFAULT_DEBUGGER "ntsd -server npipe:pipe=despoof_debug -noio"
#endif

#ifndef DESPOOF_DEFAULT_NET_MODULE
# define DESPOOF_DEFAULT_NET_MODULE "pcap"
#endif

#ifdef DESPOOF_DEFAULT_LOG_MODULE_ALL
# define DESPOOF_DEFAULT_LOG_MODULE DESPOOF_DEFAULT_LOG_MODULE_ALL
#else
# ifndef DESPOOF_DEFAULT_LOG_MODULE_NOSVC
#  define DESPOOF_DEFAULT_LOG_MODULE_NOSVC "console"
# endif

# ifndef DESPOOF_DEFAULT_LOG_MODULE_SVC
#  define DESPOOF_DEFAULT_LOG_MODULE_SVC "file"
# endif

# ifdef BUILD_SERVICE
#  define DESPOOF_DEFAULT_LOG_MODULE DESPOOF_DEFAULT_LOG_MODULE_SVC
# else
#  define DESPOOF_DEFAULT_LOG_MODULE DESPOOF_DEFAULT_LOG_MODULE_NOSVC
# endif
#endif
